export const products = [
  {
    id: 1,
    title: "Air jordan",
    price: "$100",
    category: "men's Shoe",
    image: "/shoes/1.jpg",
  },
  {
    id: 2,
    title: "Stan Maquine",
    price: "$150",
    category: "men's Shoe",
    image: "/shoes/2.jpg",
  },
  {
    id: 3,
    title: "Air for One",
    price: "$200",
    category: "men's Shoe",
    image: "/shoes/3.jpg",
  },
  {
    id: 4,
    title: "Stan Smith",
    price: "$500",
    category: "men's Shoe",
    image: "/shoes/4.jpg",
  },
  {
    id: 5,
    title: "Alexander maquine",
    price: "$270",
    category: "men's Shoe",
    image: "/shoes/5.jpg",
  },
  {
    id: 6,
    title: "Air max",
    price: "$280",
    category: "men's Shoe",
    image: "/shoes/6.jpg",
  },
  {
    id: 7,
    title: "New Balance",
    price: "$350",
    category: "men's Shoe",
    image: "/shoes/7.jpg",
  },
  {
    id: 8,
    title: "Nike cortez",
    price: "$850",
    category: "men's Shoe",
    image: "/shoes/8.jpg",
  },
];
